// <auto-generated />
using System;
using Application.Models.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application.Migrations
{
    [DbContext(typeof(LawsuitDataContext))]
    [Migration("20200409185440_PrvaVerzija")]
    partial class PrvaVerzija
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Application.Models.Kompanija", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("adresa")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("naziv")
                        .HasColumnType("varchar(40)");

                    b.HasKey("id");

                    b.ToTable("Kompanije");
                });

            modelBuilder.Entity("Application.Models.Kontakt", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("adresa")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("email")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("kompanijaid");

                    b.Property<bool>("pravnoLice");

                    b.Property<string>("telefon1")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("telefon2")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("zanimanje")
                        .HasColumnType("varchar(30)");

                    b.HasKey("id");

                    b.HasIndex("kompanijaid");

                    b.ToTable("Kontakti");
                });

            modelBuilder.Entity("Application.Models.Korisnik", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("admin");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.HasKey("id");

                    b.ToTable("Korisici");
                });

            modelBuilder.Entity("Application.Models.Lokacija", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("naslov")
                        .HasColumnType("varchar(40)");

                    b.HasKey("id");

                    b.ToTable("Lokacije");
                });

            modelBuilder.Entity("Application.Models.TipPostupka", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("naslov")
                        .HasColumnType("varchar(40)");

                    b.HasKey("id");

                    b.ToTable("TipPostupaka");
                });

            modelBuilder.Entity("Application.Models.Kontakt", b =>
                {
                    b.HasOne("Application.Models.Kompanija", "kompanija")
                        .WithMany()
                        .HasForeignKey("kompanijaid");
                });
#pragma warning restore 612, 618
        }
    }
}
