// <auto-generated />
using Application.Models.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application.Migrations
{
    [DbContext(typeof(LawsuitDataContext))]
    [Migration("20200409133039_Inicijalizacija")]
    partial class Inicijalizacija
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Application.Models.Kompanija", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("adresa")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("naziv")
                        .HasColumnType("varchar(40)");

                    b.HasKey("id");

                    b.ToTable("Kompanija");
                });
#pragma warning restore 612, 618
        }
    }
}
